### ISSUE TITLE
[ar] How to show the titles in Arabic for already translated tutorials in the side navigation menu?

### ISSUE THREAD

**Issue by mohamed-ali** [tensorflow/docs-l10n#199]
When I choose the Arabic language, for a given tutorial, like this one: https://www.tensorflow.org/tutorials/keras/classification?hl=ar, I was expecting to see the title of this already translated tutorial in Arabic in the right side navigation menu, but it's showing in English as you can see in the following picture:
 
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/2883926/79729137-55699980-82ef-11ea-890b-3dab9c932652.png">

Showing the translated tutorials' title in Arabic for already translated tutorial can be useful to reader as a visual identification of what is already in Arabic.

@lamberta
Could you explain whether it's something I can configure myself with a PR or it requires extra development?

Thanks.

**Comment by lamberta** [comment]
Hi @mohamed-ali 

The site navigation is displayed using YAML files, for example, here's the English source for the tutorials: [site/en/tutorials/_toc.yaml](https://github.com/tensorflow/docs/blob/master/site/en/tutorials/_toc.yaml).

Unfortunately, these are out-of-scope for community translations. In the past we've allowed this, but they quickly fall out of sync with the source material—and the cost is very high, since users will miss entire documents (sometimes sections). These were added to the [Do not translate list](https://github.com/tensorflow/docs-l10n#do-not-translate).

Some languages on tensorflow.org are "officially" supported, meaning we use an internal process to translate the navigation. But, at this time, Arabic is still "unofficial" and not part of this internal process. Occasionally new languages are added to the "official" list, but that depends on a number of things. Will keep Arabic in mind, though, especially as the ML community grows.
